wandb_version: 1

video_length:
  desc: null
  value: 50
img_size:
  desc: null
  value: 128
epoch:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.0003
batch_size:
  desc: null
  value: 64
seed:
  desc: null
  value: 2023
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685189930.434001
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 16
      - 23
      4: 3.10.4
      5: 0.15.3
      8:
      - 5
